### ISSUE TITLE
Python 3.6 name error

### ISSUE THREAD

**Issue by perrygeo** [mapbox/nodata#62]
```
Traceback (most recent call last):
  File "/venv/lib/python3.6/site-packages/nodata/blob.py", line 130, in blob_nodata
    rm.run(workers)
  File "/venv/lib/python3.6/site-packages/riomucho/__init__.py", line 109, in run
    for data, window in self.pool.imap_unordered(reader_worker, self.windows):
  File "/venv/lib/python3.6/site-packages/riomucho/single_process_pool.py", line 9, in imap_unordered
    yield reader_worker(i)
  File "/venv/lib/python3.6/site-packages/riomucho/__init__.py", line 34, in manualRead
    raise e
  File "/venv/lib/python3.6/site-packages/riomucho/__init__.py", line 31, in manualRead
    return work_func(srcs, window, ij, global_args), window
  File "/venv/lib/python3.6/site-packages/nodata/blob.py", line 48, in blob_worker
    if isinstance(globalArgs['selectNodata'], (int, long, float)):
NameError: name 'long' is not defined
```

`long` is gone in python 3.6. Instead we should use a more descriptive type check here, works on py2.6+:

    isinstance(n, numbers.Number)

**Comment by perrygeo** [comment]
resolved in #64
